version: "3.9"

services:
    db:
        image: postgres:15
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-bootcamp}
            POSTGRES_USER: ${POSTGRES_USER:-patcharapon}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Database password required}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "${POSTGRES_PORT:-5433}:5432"
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${POSTGRES_USER:-patcharapon} -d ${POSTGRES_DB:-bootcamp}",
                ]
            interval: 10s
            timeout: 5s
            retries: 5

    web:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            db:
                condition: service_healthy
        ports:
            - "${WEB_PORT:-3001}:3000"
        environment:
            RAILS_ENV: ${RAILS_ENV:-production}
            DATABASE_URL: "postgresql://${POSTGRES_USER:-patcharapon}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB:-bootcamp}"
            RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
            SECRET_KEY_BASE: ${SECRET_KEY_BASE}
        volumes:
            - .:/rails
            - ./config/master.key:/rails/config/master.key:ro
        restart: unless-stopped

volumes:
    postgres_data:
